@startuml
hide footbox
actor 用户 as user
control 操作 as control
entity 表现层 as view
entity 逻辑层 as service
database 数据库 as db
user -> control:输入注册信息
control ++
control -> view:发送请求
view ++
view -> service:调用逻辑层校验数据
service ++
service -> db:查询数据库
db++
return:返回查询结果
service-->view:处理结果返回到表现层
service --
view-->user:得到提示对输入进行调整或者重试
user->control:点击注册
control->view:发送请求
view->service:逻辑处理
service++
service->db:操作数据库
db++
db->db:数据保存
db-->service:返回结果
db--
service-->view:返回结果
service--
view-->user:将结果反馈到用户
view--
control--
@enduml